[global]
timeout = '10s'
strategy = 'naive'
log_level = 'error'

[[chains]]
id = 'ibc-0'
rpc_addr = 'tcp://localhost:20600'
grpc_addr = 'tcp://localhost:9090'
account_prefix = 'cosmos'
key_name = 'testkey'
store_prefix = 'ibc'
gas = 200000
clock_drift = '5s'
trusting_period = '14days'

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.peers]
primary = '493311CC5C994E4F83A93B55976F4A28CE6D91F0'

[[chains.peers.light_clients]]
peer_id = '493311CC5C994E4F83A93B55976F4A28CE6D91F0'
address = 'tcp://localhost:20600'
timeout = '10s'
trusted_header_hash = '904353CD204F907CC422F750F6ABAF414327E885E44B61EADDA11B4C83D67D3A'
trusted_height = '24'

[chains.peers.light_clients.store]
type = 'disk'
path = '/home/vitor.enes/ibc-rs/data/ibc-0/data/493311CC5C994E4F83A93B55976F4A28CE6D91F0'

[[chains.peers.light_clients]]
peer_id = '2427F8D914A6862279B3326FA64F76E3BC06DB2E'
address = 'tcp://localhost:20600'
timeout = '10s'
trusted_header_hash = '7603FA5E952BEDF451D63128E34557355C221175F03C26DA90342C688135DBB5'
trusted_height = '25'

[chains.peers.light_clients.store]
type = 'disk'
path = '/home/vitor.enes/ibc-rs/data/ibc-0/data/2427F8D914A6862279B3326FA64F76E3BC06DB2E'

[[chains]]
id = 'ibc-1'
rpc_addr = 'tcp://localhost:20601'
grpc_addr = 'tcp://localhost:9091'
account_prefix = 'cosmos'
key_name = 'testkey'
store_prefix = 'ibc'
gas = 200000
clock_drift = '5s'
trusting_period = '14days'

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.peers]
primary = '6110EDE7CF6DCA2D0C1A44C4DCADF73ED1C85D2C'

[[chains.peers.light_clients]]
peer_id = '6110EDE7CF6DCA2D0C1A44C4DCADF73ED1C85D2C'
address = 'tcp://localhost:20601'
timeout = '10s'
trusted_header_hash = 'AE9ACA2060AF6A7B8FE2617D509448BB9A0A30B244479F7BF07F9EFEB4B8D6F6'
trusted_height = '14'

[chains.peers.light_clients.store]
type = 'disk'
path = '/home/vitor.enes/ibc-rs/data/ibc-1/data/6110EDE7CF6DCA2D0C1A44C4DCADF73ED1C85D2C'

[[chains.peers.light_clients]]
peer_id = 'A885BB3D3DFF6101188B462466AE926E7A6CD51E'
address = 'tcp://localhost:20601'
timeout = '10s'
trusted_header_hash = '947F6355BAFB4FF557418CD4B494D6C8B02ACC2FBF67AE93120909CA976FEE44'
trusted_height = '15'

[chains.peers.light_clients.store]
type = 'disk'
path = '/home/vitor.enes/ibc-rs/data/ibc-1/data/A885BB3D3DFF6101188B462466AE926E7A6CD51E'

[[chains]]
id = 'ibc-2'
rpc_addr = 'tcp://localhost:20602'
grpc_addr = 'tcp://localhost:9092'
account_prefix = 'cosmos'
key_name = 'testkey'
store_prefix = 'ibc'
gas = 3000000
clock_drift = '5s'
trusting_period = '14days'

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.peers]
primary = '4AA890C80850E4F947564F34E369D2BDCE39D64D'

[[chains.peers.light_clients]]
peer_id = '4AA890C80850E4F947564F34E369D2BDCE39D64D'
address = 'tcp://localhost:20602'
timeout = '10s'
trusted_header_hash = '720E85A86CC11DFD2DCD4C2466BB42EE9897FE3938DC8BCE276F202A0991A749'
trusted_height = '4'

[chains.peers.light_clients.store]
type = 'disk'
path = '/home/vitor.enes/ibc-rs/data/ibc-2/data/4AA890C80850E4F947564F34E369D2BDCE39D64D'

[[chains.peers.light_clients]]
peer_id = 'A885BB3D3DFF6101188B462466AE926E7A6CD51E'
address = 'tcp://localhost:20602'
timeout = '10s'
trusted_header_hash = '720E85A86CC11DFD2DCD4C2466BB42EE9897FE3938DC8BCE276F202A0991A749'
trusted_height = '4'

[chains.peers.light_clients.store]
type = 'disk'
path = '/home/vitor.enes/ibc-rs/data/ibc-2/data/A885BB3D3DFF6101188B462466AE926E7A6CD51E'

