[package]
name = "bbt"
version = "0.0.1"
edition = "2018"
authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]

[dependencies]
ibc = { path = "../modules" }
relayer = { path = "../relayer" }

permutator = "0.4.0"
eyre = "0.6.5"
tracing-subscriber = "0.2.3"
